const fs = require('node:fs'), vm = require('node:vm'), assert = require('node:assert/strict');
function setup({ ua = '', pads = [], legacy = false, supported = true, blocked = false, query = '' } = {}) {
  const noop = () => {}, nodes = {}, events = {};
  const ctx = new Proxy({}, { get: (o, k) => o[k] || noop });
  const element = s => nodes[s] ||= { textContent: '', getContext: () => ctx, classList: { add: noop, remove: noop }, focus: noop };
  const navigator = { userAgent: ua };
  if (supported) navigator[legacy ? 'webkitGetGamepads' : 'getGamepads'] = () => { if (blocked) throw Error('blocked'); return pads; };
  const box = { window: {}, navigator, document: { querySelector: element, querySelectorAll: s => s === '.pad-status' ? [element('#pad')] : [], body: element('body'), addEventListener: noop }, location: { search: query }, localStorage: { getItem: () => null, setItem: noop }, URLSearchParams, console, Math, Set, addEventListener: (type, fn) => events[type] = fn, requestAnimationFrame: noop };
  vm.createContext(box);
  vm.runInContext(fs.readFileSync('src/tv-support.js', 'utf8'), box);
  return { box, nodes, pads, events, read: () => box.window.secretControls.read(), display: box.window.secretDisplay };
}
const pad = (index, buttons = []) => ({ index, id: 'Test ' + index, connected: true, mapping: 'standard', axes: [0, 0], buttons });
const first = pad(0), second = pad(3, [{ value: 1 }]);
first.axes[0] = .3;
const multi = setup({ pads: [first, null, second] });
assert(multi.read().jump, 'an active second controller is not masked by an idle first one');
first.axes[0] = 0;
second.buttons = []; second.axes[0] = -.8;
assert.equal(multi.read().axis, -.8);
second.axes[0] = .1; assert.equal(multi.read().axis, 0, 'dead zone');
second.buttons[15] = { pressed: true }; assert.equal(multi.read().axis, 1);
second.connected = false; first.connected = false;
assert.equal(multi.read().connected, false, 'disconnect clears active controller');
assert(multi.nodes['#pad'].textContent.includes('presioná un botón'));
const old = setup({ legacy: true, pads: [{ index: 0, id: 'USB', axes: [0,0,0,0,0,0,-1,0], buttons: [1,0,1] }] });
assert(old.read().jump && old.read().action, 'numeric buttons and omitted connected flag');
assert.equal(old.read().axis, -1, 'USB D-pad axes');
const blocked = setup({ blocked: true }); assert.equal(blocked.read().connected, false);
assert(blocked.nodes['#pad'].textContent.includes('bloqueó'));
const unavailable = setup({ supported: false }); assert(unavailable.nodes['#pad'].textContent.includes('no ofrece'));
assert.equal(setup({ ua: 'Mozilla SMART-TV Tizen' }).display.quality, 'low');
assert.equal(setup({ query: '?quality=2d' }).display.quality, '2d');
const auto = setup(); for (let i = 0; i < 90; i++) auto.display.sample(34);
assert.equal(auto.display.quality, 'low', 'sustained slow rendering reduces effects automatically');
const native = setup({ ua: 'Mozilla Android WebView', query: '?androidtv=1' });
assert.equal(native.display.quality, 'low', 'APK starts lightweight before renderer creation');
assert(native.nodes['#pad'].textContent.includes('Y:'), 'native controller help does not falsely report disconnected');
for (let i = 0; i < 280; i++) native.display.sample(60);
assert.equal(native.display.quality, '2d', 'persistently slow APK falls back to 2D after warmup');
native.display.set('auto');
for (let i = 0; i < 600; i++) native.display.sample(16.7);
assert.equal(native.display.quality, 'low', 'healthy APK keeps 3D lightweight');
native.display.set('low');
for (let i = 0; i < 600; i++) native.display.sample(60);
assert.equal(native.display.quality, 'low', 'explicit low quality is respected');
const stalled = setup({ query: '?androidtv=1' });
for (let i = 0; i < 220; i++) stalled.display.sample(300);
assert.equal(stalled.display.quality, '2d', 'very slow frames are not discarded from adaptation');
auto.display.set('high'); for (let i = 0; i < 100; i++) auto.display.sample(34);
assert.equal(auto.display.quality, 'high', 'explicit quality choice is respected');
auto.display.set('auto'); for (let i = 0; i < 100; i++) auto.display.sample(16.7);
assert.equal(auto.display.quality, 'high', 'healthy frame rate retains detail');
const game = setup({ pads: [pad(0)] });
vm.runInContext(fs.readFileSync('dist/game.js', 'utf8').replace('})();', 'window.inputQA={input,update};})();'), game.box);
game.pads[0].buttons[0] = { pressed: true };
assert(game.box.window.inputQA.input().jp); assert(!game.box.window.inputQA.input().jp, 'held jump fires once');
game.pads[0].buttons[0] = { pressed: false }; game.box.window.inputQA.input();
const event = keyCode => ({ keyCode, preventDefault() {}, repeat: false });
game.events.keydown(event(39)); assert.equal(game.box.window.inputQA.input().axis, 1, 'TV keyCode works without KeyboardEvent.code');
game.events.keyup(event(39)); assert.equal(game.box.window.inputQA.input().axis, 0);
game.events.keydown(event(13)); const input = game.box.window.inputQA.input();
game.box.window.inputQA.update(1/120, input); assert.equal(game.box.window.gameStatus().mode, 'play', 'TV OK starts the game');
console.log('PASS: multiple/legacy controllers, disconnection, blocked API, TV keys, input edges, lightweight default and adaptive graphics');
