const fs=require('fs'),vm=require('vm'),assert=require('assert');
const noop=()=>{},ctx=new Proxy({measureText:s=>({width:s.length*16}),createLinearGradient:()=>({addColorStop:noop}),createRadialGradient:()=>({addColorStop:noop})},{get:(o,k)=>o[k]||noop,set:(o,k,v)=>(o[k]=v,true)}),els={};
const element=s=>els[s]??=(s==='#game'?{getContext:()=>ctx}:{classList:{add:noop,remove:noop},focus:noop});
const sandbox={console,Math,Set,document:{querySelector:element,querySelectorAll:()=>[],body:{classList:{add:noop,remove:noop}},addEventListener:noop},navigator:{},window:{},addEventListener:noop,requestAnimationFrame:noop};
let src=fs.readFileSync('dist/game.js','utf8').replace('})();','window.test={update,start,reset,render,input,get p(){return player},get plats(){return platforms},get state(){return {mode,gate,switchOn,bridge,finalBridge,flags,checkpoint,queue,dialog}},setPos(x,y){player.x=x;player.y=y;player.vy=0;},clearTalk(){queue=[];dialog=null;},setMode(v){mode=v;}};})();');vm.runInNewContext(src,sandbox);const g=sandbox.window.test,I={axis:0,jump:false,jp:false,act:false,pp:false},tick=(n,inp={})=>{for(let i=0;i<n;i++)g.update(1/120,{...I,...inp,jp:i===0&&!!inp.jp,act:i===0&&!!inp.act});};
g.start();tick(120);assert(g.p.ground);const y=g.p.y;tick(30,{jump:true,jp:true});assert(g.p.y<y-90,'jump height');tick(150);assert(g.p.ground);g.setPos(1000,1050);tick(1);assert.equal(g.p.x,180,'respawn');
g.setPos(2200,600);tick(1);assert(g.state.bridge);g.setPos(3110,620);tick(1,{act:true});assert(!g.state.gate,'wrong number');g.setPos(3330,620);tick(1,{act:true});assert(g.state.gate,'correct number');g.setPos(5250,708);tick(1,{act:true});assert(g.state.switchOn,'maze switch');g.setPos(5900,640);tick(1);assert(g.state.flags.calm);tick(12000);assert(g.state.flags.calmDone,'calm resolves');g.setPos(6500,638);tick(1);assert(g.state.finalBridge);g.setPos(8700,638);tick(2);assert(g.state.flags.finale);tick(7000);assert.equal(g.state.mode,'end');g.render();g.reset();assert.equal(g.plats.length,19,'restart restores base platforms');assert(!g.state.gate);console.log('PASS: jump, landing, respawn, wrong/right answer, switch, calm, final, rendering and reset');


