const fs = require('node:fs'), vm = require('node:vm'), assert = require('node:assert/strict');
function setup({ ua = '', pads = [], legacy = false, supported = true, blocked = false, query = '' } = {}) {
  const noop = () => {}, nodes = {}, events = {};
  const ctx = new Proxy({}, { get: (o, k) => o[k] || noop });
  const element = s => nodes[s] ||= { textContent: '', getContext: () => ctx, classList: { add: noop, remove: noop }, focus: noop };
  const navigator = { userAgent: ua };
  if (supported) navigator[legacy ? 'webkitGetGamepads' : 'getGamepads'] = () => { if (blocked) throw Error('blocked'); return pads; };
  const box = { window: {}, navigator, document: { querySelector: element, querySelectorAll: s => s === '.pad-status' ? [element('#pad')] : [], body: element('body'), addEventListener: noop }, location: { search: query }, localStorage: { getItem: () => null, setItem: noop }, URLSearchParams, console, Math, Set, addEventListener: (type, fn) => events[type] = fn, requestAnimationFrame: noop };
  vm.createContext(box);
  vm.runInContext(fs.readFileSync('src/tv-support.js', 'utf8'), box);
  return { box, nodes, pads, events, read: () => box.window.secretControls.read(), display: box.window.secretDisplay };
}
const pad = (index, buttons = []) => ({ index, id: 'Test ' + index, connected: true, mapping: 'standard', axes: [0, 0], buttons });
const first = pad(0), second = pad(3, [{ value: 1 }]);
first.axes[0] = .3;
const multi = setup({ pads: [first, null, second] });
assert(multi.read().jump, 'an active second controller is not masked by an idle first one');
first.axes[0] = 0;
second.buttons = []; second.axes[0] = -.8;
assert.equal(multi.read().axis, -.8);
second.axes[0] = .1; assert.equal(multi.read().axis, 0, 'dead zone');
second.buttons[15] = { pressed: true }; assert.equal(multi.read().axis, 1);
second.connected = false; first.connected = false;
assert.equal(multi.read().connected, false, 'disconnect clears active controller');
assert(multi.nodes['#pad'].textContent.includes('presioná un botón'));
const old = setup({ legacy: true, pads: [{ index: 0, id: 'USB', axes: [0,0,0,0,0,0,-1,0], buttons: [1,0,1] }] });
assert(old.read().jump && old.read().action, 'numeric buttons and omitted connected flag');
assert.equal(old.read().axis, -1, 'USB D-pad axes');
const blocked = setup({ blocked: true }); assert.equal(blocked.read().connected, false);
assert(blocked.nodes['#pad'].textContent.includes('bloqueó'));
const unavailable = setup({ supported: false }); assert(unavailable.nodes['#pad'].textContent.includes('no ofrece'));
for (const options of [{}, { ua: 'Mozilla SMART-TV Tizen' }, { query: '?quality=2d' }, { ua: 'Mozilla Android WebView', query: '?androidtv=1' }]) {
  const fixed = setup(options).display;
  assert.equal(fixed.quality, 'high');
  assert.equal(fixed.resolution, 1);
  assert.equal(fixed.frameInterval(), 0);
  fixed.set('low');
  for (let i = 0; i < 600; i++) fixed.sample(60);
  assert.equal(fixed.quality, 'high', 'legacy preferences and slow frames cannot change detailed graphics');
  let notified; fixed.subscribe(value => notified = value);
  assert.equal(notified, 'high');
}
assert(!fs.readFileSync('dist/index.html', 'utf8').includes('quality-select'));
const game = setup({ pads: [pad(0)] });
vm.runInContext(fs.readFileSync('dist/game.js', 'utf8').replace('})();', 'window.inputQA={input,update};})();'), game.box);
game.pads[0].buttons[0] = { pressed: true };
assert(game.box.window.inputQA.input().jp); assert(!game.box.window.inputQA.input().jp, 'held jump fires once');
game.pads[0].buttons[0] = { pressed: false }; game.box.window.inputQA.input();
const event = keyCode => ({ keyCode, preventDefault() {}, repeat: false });
game.events.keydown(event(39)); assert.equal(game.box.window.inputQA.input().axis, 1, 'TV keyCode works without KeyboardEvent.code');
game.events.keyup(event(39)); assert.equal(game.box.window.inputQA.input().axis, 0);
game.events.keydown(event(13)); const input = game.box.window.inputQA.input();
game.box.window.inputQA.update(1/120, input); assert.equal(game.box.window.gameStatus().mode, 'play', 'TV OK starts the game');
const controlEvent = code => ({ code, preventDefault() {}, repeat: false });
game.events.keydown(controlEvent('KeyM')); assert.equal(game.nodes['#sound'].textContent, 'Sonido: no', 'L1-mapped sound key toggles audio once');
game.events.keydown(controlEvent('KeyY')); assert.equal(game.display.quality, 'high', 'Y cannot change fixed graphics');
console.log('PASS: multiple/legacy controllers, disconnection, blocked API, TV keys, input edges, fixed detailed graphics');
